import React, { useState } from "react";
import { useAuth } from "../context/AuthContext";
import PageHeader from "../components/PageHeader";

const API_BASE = process.env.REACT_APP_API_BASE_URL || "http://localhost:8080/api";

const AIChat = () => {
  const { token, user } = useAuth();
  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [messages, setMessages] = useState([
    {
      role: "assistant",
      text: "Hi! I am your local AI assistant powered by Ollama. Ask me anything about bookings, facilities, assets, and incidents.",
    },
  ]);

  const handleSend = async (e) => {
    e.preventDefault();
    const text = prompt.trim();
    if (!text || loading) return;

    setError("");
    setLoading(true);
    setMessages((prev) => [...prev, { role: "user", text }]);
    setPrompt("");

    try {
      const response = await fetch(`${API_BASE}/ai/chat`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ prompt: text }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || "Failed to get AI response");
      }

      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          text: data.response || "No response returned.",
        },
      ]);
    } catch (err) {
      setError(err.message || "AI chat failed");
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          text: "I could not connect to Ollama. Please ensure Ollama is running on your machine.",
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="sf-page">
      <PageHeader
        breadcrumb="Workspace / AI Assistant"
        title="AI Chat"
        subtitle={`Ask anything as ${user?.role || "USER"}. Replies are generated by your local Ollama model.`}
      />

      {error && (
        <div className="mb-4 rounded-xl border border-rose-300/40 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">
          {error}
        </div>
      )}

      <div className="sf-card p-4 sm:p-5">
        <div className="max-h-[55vh] space-y-3 overflow-y-auto pr-1">
          {messages.map((msg, idx) => (
            <div
              key={`${msg.role}-${idx}`}
              className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                msg.role === "user"
                  ? "ml-auto border border-slate-700/40 bg-slate-700/35 text-slate-100"
                  : "mr-auto border border-white/10 bg-black/35 text-slate-200"
              }`}
            >
              <p className="mb-1 text-[11px] font-semibold uppercase tracking-[0.08em] opacity-70">
                {msg.role === "user" ? "You" : "AI"}
              </p>
              <p className="whitespace-pre-wrap">{msg.text}</p>
            </div>
          ))}

          {loading && (
            <div className="mr-auto max-w-[88%] rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm text-slate-300">
              Thinking...
            </div>
          )}
        </div>

        <form onSubmit={handleSend} className="mt-4 flex gap-2">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Type your question..."
            className="sf-input min-h-[52px] flex-1 resize-y"
            rows={2}
          />
          <button type="submit" className="sf-btn-primary self-end" disabled={loading || !prompt.trim()}>
            Send
          </button>
        </form>
      </div>
    </section>
  );
};

export default AIChat;
